version: '3.8'
services:
  api:
    build: ./app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=partywatch
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mongo_data:
  redis_data: 