services:
  # Backend API
  - type: web
    name: partywatch-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Streamlit
  - type: web
    name: partywatch-frontend
    env: python
    buildCommand: pip install -r requirements_streamlit.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://partywatch-backend.onrender.com/api
      - key: PYTHON_VERSION
        value: 3.11.0 